# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      SystemWebAdapters:
        patterns:
          - "Microsoft.AspNetCore.SystemWebAdapters"
          - "Microsoft.AspNetCore.SystemWebAdapters.*"
      AspNetCore:
        patterns:
          - "Microsoft.AspNetCore.*"
      MicrosoftCodeAnalysis:
        patterns:
          - "Microsoft.CodeAnalysis.*"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions.*"
      Testing:
        patterns:
          - "Microsoft.Testing.*"
          - "MSTest"
      DotNet:
        patterns:
          - "System.*"
          - "Microsoft.*"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
