//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Optimization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OptimizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptimizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Optimization.Resources.OptimizationResources", typeof(OptimizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string BundleDirectory_does_not_exist {
            get {
                return ResourceManager.GetString("BundleDirectory_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;({0})||document.write(&apos;&lt;script src=&quot;{1}&quot;&gt;&lt;\/script&gt;&apos;);&lt;/script&gt;.
        /// </summary>
        internal static string CdnFallBackScriptString {
            get {
                return ResourceManager.GetString("CdnFallBackScriptString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Path for DynamicFolderBundles cannot start with a &apos;/&apos; or &apos;~&apos; character and it cannot contain a &apos;?&apos; character..
        /// </summary>
        internal static string DynamicFolderBundle_InvalidPath {
            get {
                return ResourceManager.GetString("DynamicFolderBundle_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string File_does_not_exist {
            get {
                return ResourceManager.GetString("File_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OptimizationMode value, valid values are: Always, WhenEnabled, WhenDisabled..
        /// </summary>
        internal static string InvalidOptimizationMode {
            get {
                return ResourceManager.GetString("InvalidOptimizationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pattern: &apos;{0}&apos;. Wildcards are only allowed in the last path segment, can contain only one leading or trailing wildcard, and cannot be used with {{version}}..
        /// </summary>
        internal static string InvalidPattern {
            get {
                return ResourceManager.GetString("InvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure wildcard search patterns &apos;*&apos; and &apos;*.*&apos; are not supported..
        /// </summary>
        internal static string InvalidWildcardSearchPattern {
            get {
                return ResourceManager.GetString("InvalidWildcardSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minification failed. Returning unminified contents..
        /// </summary>
        internal static string MinifyError {
            get {
                return ResourceManager.GetString("MinifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        internal static string Parameter_NullOrEmpty {
            get {
                return ResourceManager.GetString("Parameter_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value assigned to property &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        internal static string Property_NullOrEmpty {
            get {
                return ResourceManager.GetString("Property_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not inherit from &apos;{1}&apos;..
        /// </summary>
        internal static string Type_doesnt_inherit_from_type {
            get {
                return ResourceManager.GetString("Type_doesnt_inherit_from_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL &apos;{0}&apos; is not valid. Only application relative URLs (~/url) are allowed..
        /// </summary>
        internal static string UrlMappings_only_app_relative_url_allowed {
            get {
                return ResourceManager.GetString("UrlMappings_only_app_relative_url_allowed", resourceCulture);
            }
        }
    }
}
