// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Web.UI.WebControls;

namespace System.Web.UI;

/// <devdoc>
/// IStyleSheet represents the core functionality of a style sheet, i.e.
/// a collection of named styles.
/// </devdoc>
public interface IStyleSheet
{

    /// <devdoc>
    /// Creates a style rule for the specified selector.  Multiple rules are allowed of the
    /// same selector
    /// </devdoc>
    void CreateStyleRule(Style style, IUrlResolutionService urlResolver, string selector);

    /// <devdoc>
    /// Adds a new style rule to the style sheet and associates it with an
    /// autogenerated name. The style is rendered using the specified
    /// URL resolver.
    /// </devdoc>
    void RegisterStyle(Style style, IUrlResolutionService urlResolver);
}
