name: NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool --ignore-failed-sources
    - name: Run GitVersion
      run: dotnet gitversion /output buildserver /nofetch
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: packages
        path: |
          artifacts/webforms/package/release/*.nupkg
          artifacts/webforms/package/release/*.snupkg
    - name: Push nuget package to Azure storage
      # if: github.ref == 'refs/heads/main'
      env:
        SLEET_FEED_TYPE: azure
        SLEET_FEED_CONTAINER: feed
        SLEET_FEED_CONNECTIONSTRING: ${{secrets.SLEET_CONNECTIONSTRING}}
      run: |
        cd $GITHUB_WORKSPACE/artifacts/webforms/package/release
        dotnet tool install -g sleet
        sleet push . --skip-existing
