name: Shim Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Run type dump
      run: dotnet run -p tools/TypeDumper/TypeDumper.csproj
    - name: Validate type forwards
      run: |
        if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
          echo "Detected new APIs not included in shim"
          git diff
          exit 1
        fi
